apiVersion: v1alpha
kind: imagerunner
showConsoleLog: true
sauce:
  region: us-west-1
suites:
  - name: Sauce Orchestrate Cat Demo
    resourceProfile: c3m3
    image: andrejstevik/testingrepo:latest
    #    update the above Docker username to match your info!
    imagePullAuth:
      user: andrejstevik
      token: <token>
    workload: webdriver
    entrypoint: 'pytest test/my_test.py'
